apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: akash126/salesshop-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/appdb
        - name: SPRING_DATASOURCE_USERNAME
          value: akash
        - name: SPRING_DATASOURCE_PASSWORD
          value: A2003189
        - name: SPRING_DATA_REDIS_HOST
          value: redis
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: APP_JWT_SECRET
          value: salesshop_jwt_secret_key_2026_spring_boot
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
